### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by Zitna** [FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API#14]
Dans ton composer, ta version de php est mise à 7.2.5. Dans ton readme tu parles de 7.4. Tu peux soit forcer ta version de php à 7.4 dans ton composer, soit dire que ton site fonctionne à partir de 7.2.5. Je penche pour la première solution :D

**Comment by FlorianJourde** [comment]
Du coup c'est mis à jour. J'ai lancé un `composer update`, testé l'application, tout fonctionne toujours correctement. On est d'accord que la version de PHP indiquée dans le fichier `composer.json` n'est là qu'à titre indicatif ?

**Comment by Zitna** [comment]
Pas vraiment. Cela va chercher les packages qui correspondent à ta version de php et au numéro de version que tu as indiqué. Il peut donc y avoir un conflit. Dans ce cas-là, une alerte est remontée.

De : Florian Jourde ***@***.***>
Date : samedi, 11 février 2023 à 12:44
À : FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API ***@***.***>
Cc : Nathalie Lesourd ***@***.***>, Author ***@***.***>
Objet : Re: [FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API] composer.json (Issue #14)

Du coup c'est mis à jour. J'ai lancé un composer update, testé l'application, tout fonctionne toujours correctement. On est d'accord que la version de PHP indiquée dans le fichier composer.json n'est là qu'à titre indicatif ?

**Comment by FlorianJourde** [comment]
Ah ok, je vois ! Du coup je peux merge la branche ?

**Comment by Zitna** [comment]
Yes, merge et reteste ton installation 😃

De : Florian Jourde ***@***.***>
Date : dimanche, 12 février 2023 à 19:44
À : FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API ***@***.***>
Cc : Nathalie Lesourd ***@***.***>, Author ***@***.***>
Objet : Re: [FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API] composer.json (Issue #14)

Ah ok, je vois ! Du coup je merge la branche ?
