### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by Zitna** [FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API#17]
Attention, il faut lancer une commande en local pour créer les clés. 
`php bin/console lexik:jwt:generate-keypair`
Il ne faut pas passer les clés dans le git.

Pas sécure et on a l'erreur suivante 
`{"status":500,"message":"Unable to create a signed JWT from the given configuration."}`

**Comment by FlorianJourde** [comment]
**Notes** : Point traité dans [cette issue](https://github.com/FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API/issues/16).
