### ISSUE TITLE
Documentation API

### ISSUE THREAD

**Issue by Zitna** [FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API#18]
Tu indiques l'URL http://127.0.0.1:8000. Par exemple, chez moi, j'ai déjà un autre site lancé sur cette adresse. Du coup, il faut que je remplace toutes les URI.
Avec postman, tu peux créer des variables. Tu cliques sur le répertoire, onglet Variables. Tu enregistres ta nouvelle variable (exemple : host). Ensuite, tu peux remplacer dans toutes tes URI http://127.0.0.1:8000 par {{host}}.

Idem pour le token, tu peux le renseigner une fois pour toute ta session. Tu cliques sur le répertoire, onglet Authorization, tu choisis Bearer Token et tu enregistres ton token.
Si tu regardes un de tes entrypoint, tu verras dans Authorization `Type : Inherit auth from parent`
Et voilà !

Enfin, je vois que dans les exemples de requête, seul PHP est disponible. Or je peux vouloir interroger ton API avec la techno que je veux.

**Comment by FlorianJourde** [comment]
**Notes** : Point traité dans [cette issue](https://github.com/FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API/issues/16).
