### ISSUE TITLE
Les produits

### ISSUE THREAD

**Issue by Zitna** [FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API#19]
Ta table de produits devrait s'appeler plutôt product que phone. Si demain, tu veux vendre des iPad, c'est dommage ;)

Pour l'entrypoint /api/phones, pour l'instant, tu n'as que quelques entrées. Demain, tu peux te retrouver avec plusieurs centaines de lignes. Cela fera de trop grosses réponses... Il faudrait penser à faire de la pagination :)

**Comment by FlorianJourde** [comment]
**Notes** : Problème traité directement sur la branche principale ! Pagination traitée dans [cette issue](https://github.com/FlorianJourde/OpenClassrooms-7-Create-a-web-service-exposing-an-API/issues/20).
